### ISSUE TITLE
Programming the PAL

### ISSUE THREAD

**Issue by mamejay** [V2RetroComputing/analog#1]
Hello there.
This is probably a silly question but how is the PAL programmed?  I suspect that this is performed VIA the PICO but just wanted to confirm.  Looking to make one up and this is the only piece I am not clear on.

Thanks

**Comment by dkgrizzly** [comment]
The PAL has to be separately programmed using a suitable programmer. The exact part I'm using is an ATF16V8, and I'm programming them with an ELNEC LabProg+.

It is possible to bridge the DEVSEL line to the CARDSEL output of the PAL if you are only planning on using the VGA or Z80 modes.

In fact, the VGA mode doesn't even need the CARDSEL signal at all, but it should be terminated (pulled high) to keep the input of the level shifter happy.

Without the PAL, you would need to upload a recompiled firmware image to switch modes between VGA and Z80, since the configuration area the V2ACFG utility uses is at the end of the slot rom address space.

 

-David

 

From: mamejay ***@***.***> 
Sent: Tuesday, January 24, 2023 4:53 PM
To: V2RetroComputing/analog ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [V2RetroComputing/analog] Programming the PAL (Issue #1)

 

Hello there.
This is probably a silly question but how is the PAL programmed? I suspect that this is performed VIA the PICO butt just wanted to confirm. Looking to make one up and this is the only piece I am not clear on.

Thanks
